### ISSUE TITLE
Import in src/geolink2oereb/lib/interfaces/pyramid_oereb/__init__.py

### ISSUE THREAD

**Issue by CoNussberger** [openoereb/geolink2oereb#7]
Im src/geolink2oereb/lib/interfaces/pyramid_oereb/__init__.py wird der folgende Import gemacht.

from src.geolink2oereb.lib.interfaces.oerebkrmtrsfr.v2_0.classes import (
    OeREBKRM_V2_0_DokumentTyp,
)

Ich erhalte dann den Fehler, dass das src modul nicht gefunden wird.

Müsste der Import nicht wie folgt aussehen?

from geolink2oereb.lib.interfaces.oerebkrmtrsfr.v2_0.classes import (
    OeREBKRM_V2_0_DokumentTyp,
)

**Comment by CoNussberger** [comment]
Jetzt hats geklappt danke für die Anleitung. 
Mit etwas Probieren (liegt an unsere c2c config) hats dann auch sehr einfach funktioniert. 
Einen kleinen Verbesserungsvorschlag habe ich noch. Ich erfasse dazu einen eigenen Issue.

**Comment by vvmruder** [comment]
Dank für die Rückmeldung.
